server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 10.211.55.13
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 10.211.55.13
leyou:
  sms:
    accessKeyId: LTAI4G2AMae4ZLBruqWbL6ge # 你自己的accessKeyId
    accessKeySecret: EjCuNGBGWn3aqW9tBaekfSBbePDpCs # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_194635067 # 模板名称
