server:
  port: 80
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:  # EurekaServer地址,多个地址以','隔开
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 设置hystrix的超时时间为6000ms
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能